######################################################################
# Automatically generated by qmake (3.0) Fri Jul 12 13:57:35 2013
######################################################################

TEMPLATE = app
TARGET = finalewindows
INCLUDEPATH += .

# Input
HEADERS += gui.hpp
SOURCES += alg.cpp gui.cpp main.cpp
QT      += widgets
